management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: www.ccff.com
    port: 5672
    username: admin
    password: admin
    virtual-host: /spring-cloud
