server:
  port: 21009
spring:
  application:
    name: cloud-config-erver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiechi/spring-study.git
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:21002/eureka/

